import 'campaign_detail.dart';

extension CampaignDetailExtensions on CampaignDetail {
  CampaignDetail copyWith({
    String? id,
    String? name,
    String? serviceId,
    String? serviceName,
    String? status,
    int? totalTasks,
    int? completedTasks,
    int? inProgressTasks,
    int? pendingTasks,
    int? rejectedTasks,
    int? underReviewTasks,
    double? completionPercentage,
    double? totalAmount,
    double? spentAmount,
    String? paymentStatus,
    DateTime? createdAt,
    DateTime? originalDeadline,
    DateTime? currentDeadline,
    List<DeadlineExtension>? extensions,
    String? remainingTime,
    String? instructions,
    List<String>? proofRequirements,
    int? acceptWithinHours,
    int? completeWithinHours,
    String? reviewMode,
    double? approvalRate,
    double? rejectionRate,
    int? averageReviewTimeMinutes,
    int? pendingReviews,
  }) {
    return CampaignDetail(
      id: id ?? this.id,
      name: name ?? this.name,
      serviceId: serviceId ?? this.serviceId,
      serviceName: serviceName ?? this.serviceName,
      status: status ?? this.status,
      totalTasks: totalTasks ?? this.totalTasks,
      completedTasks: completedTasks ?? this.completedTasks,
      inProgressTasks: inProgressTasks ?? this.inProgressTasks,
      pendingTasks: pendingTasks ?? this.pendingTasks,
      rejectedTasks: rejectedTasks ?? this.rejectedTasks,
      underReviewTasks: underReviewTasks ?? this.underReviewTasks,
      completionPercentage: completionPercentage ?? this.completionPercentage,
      totalAmount: totalAmount ?? this.totalAmount,
      spentAmount: spentAmount ?? this.spentAmount,
      paymentStatus: paymentStatus ?? this.paymentStatus,
      createdAt: createdAt ?? this.createdAt,
      originalDeadline: originalDeadline ?? this.originalDeadline,
      currentDeadline: currentDeadline ?? this.currentDeadline,
      extensions: extensions ?? this.extensions,
      remainingTime: remainingTime ?? this.remainingTime,
      instructions: instructions ?? this.instructions,
      proofRequirements: proofRequirements ?? this.proofRequirements,
      acceptWithinHours: acceptWithinHours ?? this.acceptWithinHours,
      completeWithinHours: completeWithinHours ?? this.completeWithinHours,
      reviewMode: reviewMode ?? this.reviewMode,
      approvalRate: approvalRate ?? this.approvalRate,
      rejectionRate: rejectionRate ?? this.rejectionRate,
      averageReviewTimeMinutes: averageReviewTimeMinutes ?? this.averageReviewTimeMinutes,
      pendingReviews: pendingReviews ?? this.pendingReviews,
    );
  }
}
