org.gradle.jvmargs=-Xmx3072M -XX:MaxMetaspaceSize=768m -Dhttp.keepAlive=false -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2 -Dfile.encoding=UTF-8
systemProp.https.protocols=TLSv1.2
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
