org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -Dhttp.keepAlive=false -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2 -Dfile.encoding=UTF-8
systemProp.https.protocols=TLSv1.2
org.gradle.daemon=false
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=false
android.builtInKotlin=false
android.newDsl=false
kotlin.incremental=false
