import { Injectable, BadRequestException } from '@nestjs/common';
import { TaskRepository } from '../../shared/database/repositories/task.repository';
import { RewardEngineService } from '../../reward-engine/reward.service';
import { Earning, EarningStatus } from '../types/earning';

/**
 * Worker ka earning calculate karta hai based on locked task reward amount
 */
@Injectable()
export class EarningCalculator {
    constructor(
        private readonly taskRepo: TaskRepository,
        private readonly rewardEngine: RewardEngineService,
    ) { }

    async calculate(taskId: string, workerId: string): Promise<Earning> {
        const task = await this.taskRepo.findById(taskId);

        if (!task) {
            throw new BadRequestException(`Task ${taskId} not found for earning calculation`);
        }

        // Get reward snapshot or task.rewardAmount
        let rewardAmount = Number(task.rewardAmount || 0);

        if (rewardAmount <= 0) {
            const rewardSnapshot = await this.rewardEngine.getSnapshotReward(taskId).catch(() => null);
            if (rewardSnapshot?.totalReward && Number(rewardSnapshot.totalReward) > 0) {
                rewardAmount = Number(rewardSnapshot.totalReward);
            }
        }

        if (rewardAmount <= 0) {
            throw new BadRequestException(`Task ${taskId} has invalid or zero reward amount: ${task.rewardAmount}`);
        }

        const earning: Earning = {
            id: null, // Will be generated by database
            workerId,
            taskId,
            amount: Math.round(rewardAmount * 100) / 100,
            type: 'task_completion',
            status: EarningStatus.PENDING,
            metadata: {
                taskType: task.taskType,
                orderId: task.orderId,
                completedAt: new Date(),
            },
        };

        return earning;
    }
}
